@startuml
title Esboço compra de passagens

actor Cliente
participant "Servidor" as Servidor

== Conexão Cliente-Servidor ==
Cliente -> Servidor: ESTABELECER_CONEXÃO (TCP)
Cliente -> Servidor: SOLICITAR_ROTA (Belém -> Curitiba)
Servidor --> Cliente: ROTA_DISPONÍVEL (Belém->Fortaleza, Fortaleza->São Paulo, São Paulo->Curitiba)

== Consulta de Voos ==
Cliente -> Servidor: SOLICITAR_TRECHOS (Belém->Fortaleza, Fortaleza->São Paulo, São Paulo->Curitiba)
Servidor --> Cliente: TRECHOS (Belém->Fortaleza, Fortaleza->São Paulo, São Paulo->Curitiba, Assentos Disponíveis: 1)

== Reserva de Trecho ==
Cliente -> Servidor: RESERVAR_TRECHO (Belém->Fortaleza, Assento 1)
Servidor --> Cliente: RESERVA_CONFIRMADA (Trecho Belém->Fortaleza, Assento 1)

Cliente -> Servidor: RESERVAR_TRECHO (Fortaleza->São Paulo, Assento 1)
Servidor --> Cliente: RESERVA_CONFIRMADA (Trecho Fortaleza->São Paulo, Assento 1)

== Confirmação de Compra ==
Cliente -> Servidor: CONFIRMAR_COMPRA
Servidor --> Cliente: COMPRA_CONCLUIDA

== Liberação de Trecho ==
Cliente -> Servidor: CANCELAR_RESERVA
Servidor --> Cliente: TRECHO_LIBERADO (Belém->Fortaleza, Fortaleza->São Paulo, São Paulo->Curitiba, Assentos disponíveis: 1)

@enduml
