@startuml
title VendePass
actor Cliente
participant "Servidor" as Servidor

Cliente -> Servidor: SOLICITAR_TRECHOS (Salvador, Fortaleza)
Servidor --> Cliente: TRECHOS (Salvador->Recife, Recife->Fortaleza)

Cliente -> Servidor: RESERVAR_ASSENTO (Salvador->Recife, Assento 1, Recife->Fortaleza, Assento 1)
Servidor --> Cliente: RESERVA_CONFIRMADA (Trecho Salvador, Fortaleza, Assento 1)

Cliente -> Servidor: CONFIRMAR_COMPRA
Servidor --> Cliente: COMPRA_CONCLUIDA

Cliente -> Servidor: CANCELAR_RESERVA
Servidor --> Cliente: TRECHOS_LIBERADO (Salvador->Recife, Recife->Fortaleza, Assento 1)

@enduml
